name: CustomItemTest
version: '1.0-SNAPSHOT'
main: net.kitsuakihiko.Main
api-version: '1.21'
authors: [ AngelShiina, Kitsuakihiko ]
commands:
  speedsword:
    description: gives you a speedsword
    permission: swords.get.speedsword
  heavysword:
    description: gives you a heavysword
    permission: swords.get.heavysword

permissions:
  swords.get.speedsword:
    default: op
  swords.get.heavysword:
    default: op