name: CustomItemTest
version: '1.0-SNAPSHOT'
main: net.kitsuakihiko
api-version: '1.21'
authors: [ AngelShiina, Kitsuakihiko ]
commands:
  speedsword:
    description: gives you a speedsword
    permission: speedsword.get

permissions:
  speedsword.get:
    default: op