name: custom-item-template
version: '1.0-SNAPSHOT'
main: de.angelshiina.Main
api-version: '1.21'
authors: [ AngelShiina ]
commands:
  speedsword:
    description: gives you a speedsword
    permission: swords.get.speedsword
  heavysword:
    description: gives you a heavysword
    permission: swords.get.heavysword

permissions:
  swords.get.speedsword:
    default: op
  swords.get.heavysword:
    default: op